datatablePath = src\\main\\resources\\BTNBest - Claim Benefit.xlsx

#web
browser = Chrome
headless = false

#Mobile (Android or iOS)
platformName = Android
browser/native = native
urlServer = http://localhost:4723
newCommandTimeout = 60

#android
appPackage = com.example.myapp
appActivity = com.example.myapp.MainActivity

#ios
bundleId = com.example.myapp
udID = 1234567890abcdef
platformVersion = 15.0
deviceName = Redmi 13C